### ISSUE TITLE
embedding content in metadata

### ISSUE THREAD

**Issue by heycitizen** [kasperisager/vanilla-oembed#5]
Hi,

This plugin is creating embeddable content for all links. Not just the ones in the user posts. 

This includes, any links in the og metadata http://ogp.me/
These are located between the ```<head>``` tags of the page. 

The causes (I suspect) are specifically these tags:
```html
<head>
....
<meta property="og:description" content="look: http://imgur.com/gallery/C99i3pW">
<meta name="description" property="og:description" itemprop="description" content="look: http://imgur.com/gallery/C99i3pW">
...
</head>
```

The obvious solution would be to only search for URLs in the ```<body>``` tag (or a particualy set of divs).

However my programming knowledge is limited, and vanilla is sparsely documented.
Any help/tips will be appreciated. 

cheers

**Comment by kasperisager** [comment]
There's currently no way to reliably fix this issue as the global anchor hook is being used, which provides no context for the link.
